### ISSUE TITLE
Visualizer?

### ISSUE THREAD

**Issue by QtSignalProcessing** [fracgawd/kitti_motion_compensation#1]
Hello @fracgawd,

Thank you for the nice work and I am working on a related project as my hobby project.
I am developing a simple tool for visualizing image(s), point cloud, and Lidar-cam calibration results together. (https://github.com/QtSignalProcessing/cam_lidar_visualizer)

If you think it's nice to have a visualizer I can try to integrate what I've developed into your project.
Looking forward to hearing from you.

**Comment by fracgawd** [comment]
Hellow @QtSignalProcessing, thanks a lot for reaching out. I recently added an example where the raw and motion compensated pointclouds get project onto the image (https://github.com/fracgawd/kitti_motion_compensation#run-examples), making it easy for people to visualize the effect.

I think this one of the easiest ways to visualize the algorithm. If you have suggestions/PRs that can help make this even better I would be happy to look at them.

Thanks!
