### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Ecalpal** [fracgawd/kitti_motion_compensation#2]
Thank you for your interesting work!

This is a significant engineering practice issue, and I am glad that someone has noticed it.

Since eigen_benchmark has provided more accurate depth maps using multi-frame disparity refinement for evaluation, I believe your work would be more useful during the training stage for individuals working on RGB+LiDAR fusion.

Do you have any plan to develop a python version?

**Comment by fracgawd** [comment]
Hello @Ecalpal and thinks for reaching out. I am happy to hear that you appreciate the work and thank you for your comments on the evaluation metric.

At current there is no plan to add python bindings, but I tried to make the library as easy as possible to get up and running (https://github.com/fracgawd/kitti_motion_compensation#running-the-thing).

I would be happy to consider a PR adding python bindings to the C++ library, or to work together on a pure Python version.

Have a nice day :100:
